version: '3.1'
services:
  mysql:
    image: docker.io/mysql:5.7
    container_name: mycontainer
    restart: always
    secrets:
      - mypass
      - mydatabase
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mypass"
      MYSQL_DATABASE_FILE: "/run/secrets/mydatabase"
    volumes:
      - "/var/lib/mysql"
secrets:
   mypass:
     file: ./mypass.txt
   mydatabase:
     file: ./mydatabase.txt
