version: '3.1'
services:
  mysql: 
    image: docker.io/mysql:5.7
    secrets:
      - mypass
      - mydatabase
    environment:
      MYSQL_DATABASE_FILE: 'mydatabase'
      # Password for root access
      MYSQL_ROOT_PASSWORD_FILE: 'mypass'
secrets:
   mypass:
     file: ./mysql_password 
   mydatabase:
     file: ./mysql_databas
