version: '3.1'
services:
  mysql: 
    image: docker.io/mysql:5.7
    secrets:
      - mypass
      - mydatabase
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_ROOT_PASSWORD: 'mypass'
secrets:
   mypass:
     file: ./mysql_password 
   mydatabase:
     file: ./mysql_database
