version: '3.1'
services:
  mysql: 
    image: docker.io/mysql:5.7
    restart: always
    secrets:
      - mypass
      - mydatabase
    environment:
      MYSQL_ROOT_PASSWORD: "/run/secrets/mypass.txt"
      MYSQL_DATABASE: "/run/secrets/mydatabase.txt"
secrets:
   mypass:
     file: /run/secrets/mypass.txt
   mydatabase:
     file: /run/secrets/mydatabase.txt
